/**
 * The Node entry point: everything the package exports.
 *
 * Narrower entries exist for consumers who must not pay for all of it:
 *
 *   `/verdict`  — zero dependencies, for reading a stored score back.
 *   `/headers`  — zero dependencies, for reading raw header text.
 *   `/attachments` — zero dependencies, the attachment stage on its own.
 *   `/identity` — `tldts` only, for the sender rule.
 *   `/links`    — the deceptive-link checks.
 *   `/security` — the level decision, for a UI that displays one.
 *   `/content`  — the body-content stage.
 *   `/scan`     — the whole pipeline over a raw message; the one entry that
 *                 costs a MIME parser.
 *   `/verify`   — opt-in SPF/DKIM/DMARC verification against DNS; one of the
 *                 two entries that can make a network call, and the only one
 *                 whose dependency (`mailauth`) is an optional peer.
 *   `/reputation` — opt-in DNS blocklist lookups; the other entry that can
 *                 make a network call, and the only Node-only one.
 *
 * All are re-exported here, so a Node consumer needs one import and a browser
 * consumer can still avoid the address parser, the freemail corpus and the
 * MIME parser.
 */
export {
  extractOriginIp,
  isPublicIp,
  normalizeIp,
  originIpFromAuthHeaders,
  originIpFromReceived,
  type OriginIpSources,
} from './headers/origin-ip.js';
export {
  bulkHeaderSignals,
  extractAuthHeaderBlock,
  hasBulkHeaderSignal,
  headerLookupFromText,
  headerValueFromText,
  headerValuesFromText,
  parseAuthenticationHeaders,
  parseAuthResultsHeader,
  receivedAt,
  receivedAtFromLine,
  BULK_HEADER_NAMES,
  type AuthResult,
  type AuthResultsHeader,
  type AuthResultsOptions,
  type BulkHeaderSignals,
  type HeaderLookup,
} from './headers/index.js';
export {
  scan,
  scanMany,
  scanParsed,
  trustedAuthHeaders,
  type BulkScanInput,
  type BulkScanOptions,
  type BulkScanResult,
  type RawMessage,
  type ScannedMessage,
  type ScanOptions,
  type ScanResult,
} from './scan.js';
export {
  assessSpamSignals,
  isFreemailAddress,
  DATE_SKEW_SECONDS,
  SPAM_HEADER_NAMES,
  type SpamSignalInput,
} from './rules/header-rules.js';
export { FREEMAIL_DOMAINS } from './data/freemail-domains.js';
export { hasReplyPrefix, isValidMessageId } from './rfc.js';
export {
  assessSender,
  brandOwningDomain,
  brandsNamedIn,
  domainCarriesBrandName,
  domainOfAddress,
  domainsInText,
  impersonatedBrand,
  registrableDomain,
  PROTECTED_BRANDS,
  type PhishingReason,
  type ProtectedBrand,
} from './identity.js';
export {
  anchorMismatches,
  linkTarget,
  shownDomains,
  urlsInText,
  LINK_WRAPPER_DOMAINS,
  type AnchorLike,
  type LinkMismatch,
  type LinkTarget,
} from './urls.js';
export {
  assessLinks,
  assessPhishing,
  linkDomains,
  linkDomainsAllMatch,
  linkMismatches,
  summarizeLinkDomains,
  LINK_DOMAINS_MAX,
  type LinkDomainsOptions,
  type LinkDomainSummary,
  type OffDomainLink,
  type PhishingAssessment,
  type PhishingLevel,
} from './links.js';
export {
  assessContentSignals,
  bodyContent,
  collapseWhitespace,
  containsPhrase,
  extractHtml,
  longestShoutRun,
  matchSpamVocabulary,
  normalizeForMatching,
  ownWords,
  stripQuotedTail,
  vocabularyPoints,
  QUOTE_MARKERS,
  SPAM_PHRASE_GROUPS,
  VOCABULARY_CAP,
  type BodyContent,
  type ContentSignalInput,
  type HtmlAnchor,
  type HtmlExtract,
  type HtmlLink,
  type SpamPhraseGroup,
  type VocabularyHit,
} from './content/index.js';
export {
  asBytes,
  assessAttachmentSignals,
  expectedTypesForExtension,
  expectedTypesForMimeType,
  extensionsOf,
  inspectAttachment,
  inspectFilename,
  isExecutableType,
  listZipEntries,
  sniffFileType,
  stripBidiControls,
  ARCHIVE_EXECUTABLE_EXTENSIONS,
  ARCHIVE_EXTENSIONS,
  DECOY_EXTENSIONS,
  EXECUTABLE_EXTENSIONS,
  MACRO_ENABLED_EXTENSIONS,
  type AttachmentContent,
  type AttachmentFacts,
  type AttachmentInput,
  type FilenameFacts,
  type SniffedType,
  type TypeMismatch,
  type ZipEntry,
  type ZipListing,
} from './attachments/index.js';
export {
  assessEmailSecurity,
  linkRuleKey,
  parseAuthStatus,
  worstLevel,
  EMPTY_RULES,
  LEVEL_RANK,
  type BrandIdentity,
  type CheckStatus,
  type LinkRuleSets,
  type SecurityAssessment,
  type SecurityCheck,
  type SecurityInput,
  type SecurityLevel,
} from './security.js';
export {
  assessmentOf,
  canonicalReasonId,
  isSpamScore,
  mergeAssessments,
  authenticationFailed,
  parseSpamReasons,
  rollUpAuthStatus,
  spamVerdict,
  stageOfReason,
  unknownAuthStatus,
  SPAM_REASON_STAGES,
  SPAM_THRESHOLD,
  SUSPICIOUS_THRESHOLD,
  type AuthStatus,
  type SpamAssessment,
  type SpamReason,
  type SpamReasonId,
  type SpamStage,
  type SpamVerdict,
} from './verdict.js';
export {
  authVerificationFrom,
  verifyAuthentication,
  type AuthVerification,
  type DnsResolver,
  type MailauthDmarc,
  type MailauthResult,
  type MailauthSignature,
  type MailauthSpf,
  type MailauthStatus,
  type VerifiedSignature,
  type VerifyInput,
  type VerifyOptions,
} from './verify.js';
export {
  assessReputation,
  blocklistQueryName,
  checkReputation,
  checkReputationBatch,
  normalizeQueryDomain,
  readBlocklistCodes,
  reverseIpLabel,
  BARRACUDA,
  BLOCKLISTS,
  REPUTATION_MAX_POINTS,
  SPAMCOP,
  SPAMHAUS_DBL,
  SPAMHAUS_ZEN,
  SURBL,
  URIBL,
  USER_REPORT_POINTS,
  USER_REPORTS_MIN,
  type AssessReputationOptions,
  type Blocklist,
  type BlocklistCategory,
  type BlocklistCode,
  type BlocklistHit,
  type BlocklistKind,
  type CodeReading,
  type DnsQuery,
  type DnsRecordType,
  type DnsResolverOptions,
  type ReputationBatchOptions,
  type ReputationLookupError,
  type ReputationOptions,
  type ReputationResult,
  type ReputationTarget,
} from './reputation.js';
export {
  assessDomainAge,
  domainAgePoints,
  fetchRdapBootstrap,
  lookupDomainAge,
  rdapServerFor,
  DOMAIN_AGE_MAX_POINTS,
  DOMAIN_AGE_TIERS,
  RDAP_BOOTSTRAP_URL,
  RDAP_MAX_BYTES,
  type AssessDomainAgeOptions,
  type DomainAgeLookup,
  type DomainAgeOptions,
  type DomainAgeStatus,
  type DomainAgeSubjects,
  type RdapBootstrap,
} from './age.js';
export {
  checkBimiSvg,
  decodeLogoDataUri,
  defaultFetch,
  discoverFavicon,
  dmarcEnforcesBimi,
  extractIconLinks,
  extractLogotypeEvidence,
  faviconHosts,
  fetchBounded,
  fingerprintHex,
  lookupBimi,
  parseBimiRecord,
  parseDmarcRecord,
  rankIconCandidates,
  sniffImageType,
  validateVmc,
  vmcDomains,
  BIMI_EKU_OID,
  BIMI_EVIDENCE_MAX_BYTES,
  BIMI_LOGO_MAX_BYTES,
  BIMI_SELECTOR,
  FAVICON_MAX_BYTES,
  HOMEPAGE_MAX_BYTES,
  LOGOTYPE_EXTENSION_OID,
  MVA_ROOTS,
  type BimiLookup,
  type BimiOptions,
  type BimiRecord,
  type BimiStatus,
  type DmarcPolicyValue,
  type DmarcRecord,
  type FaviconOptions,
  type FaviconResult,
  type FaviconStatus,
  type FetchBoundedOptions,
  type FetchedBytes,
  type FetchLike,
  type FetchResponse,
  type IconCandidate,
  type LogotypeEvidence,
  type MarkVerifyingAuthorityRoot,
  type SvgCheck,
  type ValidateVmcOptions,
  type VmcResult,
  type VmcStatus,
} from './brand/index.js';
